### ISSUE TITLE
Пакетное логирование (таблица ulog_pkt). Оно сохраняет только raw_pktlen, raw_pktcount, oob_prefix, oob_time_sec, oob_time_usec, oob_mark, oob_hook, oob_uid, oob_gid.

### ISSUE THREAD

**Issue by AlexanderARodin** [Zapunidi/ulogd_sqlite3_html#1]
`stack=log20:NFLOG,base1:BASE,ifi1:IFINDEX,ip2str1:IP2STR,boot_sqlt:SQLITE3` вот так всё сохраняет.
Ключ - плагин BASE, который все это парсит и "достает".
Далее там плагины просто для преобразования в удобочитаемый вид имён интерфейсов, айпи-адресов.. можно добавить парсер мак-адресов (у меня обычно он добавлен).
Разумеется, для того, чтобы база это все взяла, нужно ей схему с нужными полями сделать, например `ip_saddr_str   TEXT` создаст поле, куда будет извлекаться преобразованый в удобочитаемый вид адрес источника (обе версии - 4 и 6).
Как-то так..

З.Ы.: единственно, я не смог некоторые поля удобно звлечь, например, `l4_sport`. формально это находил как поле, которое читает BASE, но вот потом в SQLite3 никак его задействовать не получается.. только раздельно читать порты TCP и UDP соответственно.

**Comment by Zapunidi** [comment]
Спасибо за информацию. А какие поля и какого типа нужно создать в SQL? Я брал готовую таблицу из примеров, а документации по возможным полям не нашёл.

**Comment by AlexanderARodin** [comment]
В мануале Ulog2d много примеров. Даже избыточно.
Но подвох в том, что они все НЕ для SQLite, а для других БД. А для SQLite пример весьма ограниченный.

Вот из других примеров по аналогии я навыуживал наименование полей, выписал в условную схему, которую тестировал уже на работоспособность в SQLIte: https://github.com/AlexanderARodin/deployULOGD2/blob/main/sqlt3-schm/field-list.schema

Ещё стоит отметить, что некоторые поля (например, все с суффиксом *_str*) отсутствуют в исходном потоке, а являются продуктом использования плагинов-дешифраторов перед SQLite. У меня в примере конфига можно найти: https://github.com/AlexanderARodin/deployULOGD2/blob/main/etc/ulogd.conf

Подозреваю, что это не полный перечень. Но для старта может хватить, если нужно и\или интересно чуть углубиться.
